In [24]:
import numpy as np
import pandas as pd

a = np.array([1,2,3])
b = np.array([4,5,6])

# vstack, hstack 안에 반드시 인자 1개만 들어가야하고, 튜플로 만들어서 넣어줘야함
# vstack은 수직으로 쌓아 올린다라고 생각하면 됨
print(np.vstack((a, b, [7,8,9])))

# hstack은 수평으로 붙여나간다고 생각하면되고, 리스트를 수평으로 붙여버림
print(np.hstack((a, b, [7,8,9])))



df = pd.DataFrame({
    'key1' : ['a', 'a', 'b', 'b', 'a']
    , 'key2' : ['one', 'two','one', 'two','one']
    , 'data1' : np.random.randn(5)
    , 'data2' : np.random.randn(5)
})

print(df)

print(df['data1'].groupby(df['key1']))

# key1으로 그룹바이 된 결과 a, b 항목에 대한 수치값의 산술평균을 반환
print(df['data1'].groupby(df['key1']).mean())

# key1을 기준으로 그룹바이 한 결과 모든 수치값에 대한 산술평균을 계산해서 반환
print(df.groupby('key1').mean())

# 키를 기준으로 groupby 된 결과 데이터를 표시
# 독특한건, 어쨌든 테이블 내의 모든 데이터에 대해서 수행되는거라서 a, b 2개행만 반환되는게 아니라 key2까지 고려해서 처리됨
for name, group in df.groupby('key1'):
    print(f"name={name}")
    print(f"group={group}")
    
    
print(list(df.groupby('key1')))

print(dict(list(df.groupby('key1'))))

print(dict(list(df.groupby('key1')))['a'])

print(type(dict(list(df.groupby('key1')))['a']))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
  key1 key2     data1     data2
0    a  one -2.216969 -0.096172
1    a  two  0.925912 -1.405410
2    b  one  0.661723 -0.463478
3    b  two -1.391843  1.362122
4    a  one  1.700487 -0.463686
<pandas.core.groupby.generic.SeriesGroupBy object at 0x000001603915D348>
key1
a    0.136477
b   -0.365060
Name: data1, dtype: float64
         data1     data2
key1
a     0.136477 -0.655089
b    -0.365060  0.449322
name=a
group=  key1 key2     data1     data2
0    a  one -2.216969 -0.096172
1    a  two  0.925912 -1.405410
4    a  one  1.700487 -0.463686
name=b
group=  key1 key2     data1     data2
2    b  one  0.661723 -0.463478
3    b  two -1.391843  1.362122
[('a',   key1 key2     data1     data2
0    a  one -2.216969 -0.096172
1    a  two  0.925912 -1.405410
4    a  one  1.700487 -0.463686), ('b',   key1 key2     data1     data2
2    b  one  0.661723 -0.463478
3    b  two -1.391843  1.362122)]
{'a':   key1 key2     data1     data2
0    a  one -2.216969 -0.096172
1    a  two  0.925912 -1.405410
4    a  one  1.700487 -0.463686, 'b':   key1 key2     data1     data2
2    b  one  0.661723 -0.463478
3    b  two -1.391843  1.362122}
  key1 key2     data1     data2
0    a  one -2.216969 -0.096172
1    a  two  0.925912 -1.405410
4    a  one  1.700487 -0.463686
<class 'pandas.core.frame.DataFrame'>